In [1]:
import torch
import torch.nn as nn

In [16]:
ious = torch.rand(2 , 4)
a,b = torch.max(ious, dim = 0)
print(ious)
print (a)
print(b)

tensor([[0.1414, 0.8267, 0.6960, 0.0569],
        [0.9883, 0.9969, 0.8449, 0.0186]])
tensor([0.9883, 0.9969, 0.8449, 0.0569])
tensor([1, 1, 1, 0])
